# -*- coding: utf-8 -*-
"""DZ4_stoh.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1eDaYq-4bMVtOUc-eBQ3t3FVLWFgSNCKL
"""

import numpy as np
import pandas as pd
from scipy.stats import norm
import random
import matplotlib.pyplot as plt

T=7
r=0.1
b=0.8
h=0.5
n=70

#N=T/h
N=14


ksi=np.zeros(N)
ksi[0]=100

X=np.zeros(N)
X[0]=ksi[0]

t=np.arange(0, T+h, h)
print(t)

W=np.zeros(N)
for i in range(1, N):
  W[i]=W[i-1]+np.random.normal(0, np.sqrt(h))
print(W)

for i  in range(1,N):
  ksi[i]=ksi[0]*np.exp((r-b**2/2)*t[i]+b*W[i])
print(ksi)

for i  in range(1,N):
  X[i]=X[i-1]+r*X[i-1]*h+b*X[i-1]*(W[i]-W[i-1])

print(X)

plt.plot(t, ksi)
plt.plot(t, X)
plt.legend(["ksi", "X"])
plt.show()

h_l=[0.5, 0.1, 0.05, 0.01, 0.005, 0.001, 0.0005, 0.0001]

def variant_step(h, index):
  s=0
  for j in range(n):
    N=int(T/h)
    t=np.arange(0, T, h)
    ksi=np.zeros(N)
    ksi[0]=100
    X=np.zeros(N)
    X[0]=100
    W=np.zeros(N)
    for i in range(1,N):
      W[i]=W[i-1]+np.random.normal(0, np.sqrt(h))
      ksi[i]=ksi[0]*np.exp((r-b**2/2)*t[i]+b*W[i])
      X[i]=X[i-1]+r*X[i-1]*h+b*X[i-1]*(W[i]-W[i-1])
    s+=np.abs(X[N-1]-ksi[N-1])
  e_h=float(s)/n
  print("e", index, "=", e_h)
  plt.plot(t, ksi)
  plt.plot(t, X)
  plt.legend(["ksi", "X"])
  plt.show()

for i in range(8):
 variant_step(h_l[i], i+1)

F=np.zeros((8,2))
for i in range(8):
  F[i][0]=1
  F[i][1]=np.log(h_l[i])

print(F)

c=[np.log(151.3743077075018),np.log(60.95339264154406), np.log(41.797266812803), np.log(11.421830235229047), np.log(3.679810361101458), np.log(5.798252423072691), np.log(1.713418845049547), np.log(0.8624418278672346)]

print(c)

beta=(np.linalg.inv(F.T.dot(F)).dot(F.T)).dot(c)
print(beta)

from scipy.stats import gamma
import matplotlib.pyplot as plt
import numpy as np
x=np.arange(-5, 5, 0.001)
p=gamma.ppf(x,0.4, 9)
x1=[1,2,4,5,8]
plt.plot(x, p)

plt.show()